version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    working_dir: /app
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - mongo
    command: ["npm", "run", "start:${NODE_ENV}"]
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
