version: "3.8"

services:
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGO_URI=mongodb+srv://samuelzentou:ALXw7u95CEm6k4ZC@cluster0.zylx2ez.mongodb.net/RetroMetroidApp
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: ["node", "app.js"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
